<? app::asset('view/mustachetest.main', 'js') ?>
<div class="row">
	<div class="span6 offset3">
		<h1>
			Mustache Rendering
		</h1>
<pre>
<?= h("<?= r('mustachetest', 'template') ?>") ?>
</pre>
		<h2>
			PHP Rendered
		</h2>
		<p>
			This output was generated by the server side. 
			Just after this output, is a <code><?= h('<script>') ?></code>
			tag containing the mustache template for this output.
		</p>
		<div class="well">
			<?= r('mustachetest', 'template') ?>
		</div>
		<h2>
			JavaScript Rendered
		</h2>
		<p>
			After an AJAX request for JSON data,
			using the mustache template, the view
			is rendered.
		</p>
		<div id="append-to-me" class="well scrolling">
		</div>
	</div>
</div>
